### ISSUE TITLE
Copy-for-ChatGPT version 0.3.7 no longer working with ChatGPT Mar 23 Version

### ISSUE THREAD

**Issue by dliedke** [SethuSenthil/Copy-for-ChatGPT#13] opened 2023-04-07 12:03 UTC
Version 0.3.7 is no longer working with ChatGPT free or plus.
I submitted a PR to get this fixed.
Thanks!

**Comment by SethuSenthil** [comment] 2023-04-10 22:55
Hey! This seems to be a duplicate of #11 which I resolved in a2076fe868f3a5b8639c2603277bfd0183ae6c59, Thanks for your pull request! I will review and merge them if possible, I have custom implementations of some features already so it conflicts with my beta branch

**Closed as completed by SethuSenthil** 2023-04-10 22:55 UTC
